import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rulesDirectory = path.join(projectRoot, "prompt-compiler", "rules");
const bundlePath = path.join(projectRoot, "prompt-compiler", "rules-bundle.js");

const RULE_FILES = {
  aliasesEn: "aliases.en.json",
  aliasesRu: "aliases.ru.json",
  ambiguityRules: "ambiguity-rules.json",
  bannedFluff: "banned-fluff.json",
  bypassRules: "bypass-rules.json",
  domainRules: "domain-rules.json",
  intents: "intents.json",
  modules: "modules.json",
  outputStructures: "output-structures.json",
  protectedPatterns: "protected-patterns.json",
  slotSchemas: "slot-schemas.json",
  validationRules: "validation-rules.json"
};

export async function readRuleSources() {
  const rules = {};
  const sourceChunks = [];
  for (const [key, filename] of Object.entries(RULE_FILES)) {
    const source = await readFile(path.join(rulesDirectory, filename), "utf8");
    try {
      rules[key] = JSON.parse(source);
    } catch (error) {
      throw new Error(`${filename} contains invalid JSON: ${error.message}`);
    }
    sourceChunks.push(`${filename}\n${source}`);
  }
  rules.bundleVersion = 1;
  rules.sourceDigest = createHash("sha256").update(sourceChunks.join("\n")).digest("hex");
  return rules;
}

export function serializeRuleBundle(rules) {
  return `/* Generated by scripts/build-rules.mjs. Edit prompt-compiler/rules/*.json instead. */\n` +
    `(() => {\n  \"use strict\";\n  globalThis.GPT_MODS_PROMPT_RULES = Object.freeze(${JSON.stringify(rules, null, 2)});\n})();\n`;
}

export async function buildRuleBundle() {
  const rules = await readRuleSources();
  const source = serializeRuleBundle(rules);
  await writeFile(bundlePath, source, "utf8");
  return { bundlePath, rules, source };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { rules } = await buildRuleBundle();
  console.log(`Generated rules-bundle.js: ${rules.intents.length} intents, ${rules.modules.length} modules, ${rules.sourceDigest.slice(0, 12)}.`);
}
